---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    groups:
      # Group security updates for npm dependencies
      # into a single pull request
      npm:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
